services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: adminPillenschlucker
      POSTGRES_PASSWORD: pille3000
      POSTGRES_DB: vuedb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
